version: '3.8'
services:
  postgres-api:
    image: postgres:13
    container_name: postgres-api
    networks:
      - node-network
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_api:/var/lib/postgresql/data
    ports:
      - '5432:5432'

networks:
  node-network:
    driver: bridge

volumes:
  postgres_bot_data:
  postgres_api:
